
== Lambda

=== ¿Qué es?

Es un método anónimo que no necesita de un identificador para ser invocado

NOTE: ( parámetros ) -> expresión

[ cols="^.^1a,^.^1a", grid="cols" ]
|===
| Java 7 | Java 8

2+|
[source, java, numbered]
----
List<String> myList = new ArrayList<>();
myList.add("item");
myList.add("item");
myList.add("item");
----

<|
[source, java, numbered]
----
Collection.sort( myList, new Comparator<String>() {
  @Override
  public int compare ( String s1, String s2 ) {
    return s1.compareTo(s2);
  }
});
----

|
[source, java, numbered]
----
Collection.sort( myList, ( String s1, String s2 ) -> s1.compareTo(s2);
----
|===


=== Sintaxis

Podemos definir funciones lambda de las siguientes maneras


[ cols="^.^h,.^6a", grid="rows" ]
|===
| Simple |[source, java, numbered]
----
Collection.sort( myList, ( String s1, String s2 ) -> s1.compareTo(s2);
----

| Return |[source, java, numbered]
----
Collection.sort( myList, ( String s1, String s2 ) -> {return s1.compareTo(s2)};
----

| Sin tipo de parametro |[source, java, numbered]
----
Collection.sort( myList, ( s1, s2 ) -> {return s1.compareTo(s2)};
----

| Sin parametros |[source, java, numbered]
----
Collection.sort( myList, () -> {
  String s1 = "Hello";
  String s2 = "World";
  return s1.compareTo(s2);
};
----
|===

=== Lambda Scopes

Comportamiento de las expresiones Lambda con el alcance o ambito de las variables


Variable Local, es opcional declararla como *final* pero no podrás reasignar su valor

[source, java, numbered]
----
public String lambdaScope() {
  final String s1 = "Hello"

  Greeting greeting = ( s2 ) -> {
      return s1 + s2;
  };

  return greeting.say("World");
}
----

Variable Global, tienen el mismo comportamiento anonimos que se instancia a traves de una interface

[source, java, numbered]
----
public class Lambda {
  private static String s1 = "Hello";
  private String s3;

  public String lambdaScope() {

    Greeting greeting = ( s2 ) -> {
      s1 = s2
      s3 = s1
      return s3;
    };

    return greeting.say("World");
  }
}
----
